<a href="https://colab.research.google.com/github/Priya-gawhane/Machine-learning-prediction-Models-Projects/blob/main/Recognizing_Handwritten_digits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the dependencies

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import datasets
from sklearn.neural_network import MLPClassifier


Data collection and preprocessing

In [21]:
digits = datasets.load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [22]:
print(digits.images[0])

[[ 0.  0.  5. 13.  9.  1.  0.  0.]
 [ 0.  0. 13. 15. 10. 15.  5.  0.]
 [ 0.  3. 15.  2.  0. 11.  8.  0.]
 [ 0.  4. 12.  0.  0.  8.  8.  0.]
 [ 0.  5.  8.  0.  0.  9.  8.  0.]
 [ 0.  4. 11.  0.  1. 12.  7.  0.]
 [ 0.  2. 14.  5. 10. 12.  0.  0.]
 [ 0.  0.  6. 13. 10.  0.  0.  0.]]


In [23]:
def plot_multi(i):
  nplots = 16
  fig = plt.figure(figsize=(15, 15))
  for j in range(nplots):
    plt.subplot(4, 4, j+1)
    plt.imshow(digits.images[i+j], cmap='Heatmap')
    plt.title(digits.targets[i+j])
    plt.axis('off')
  plt.show()
  plot_multi(0)

Training neural network with the dataset

In [24]:
y = digits.target
x = digits.images.reshape((len(digits.images)),-1)

In [25]:
x.shape

(1797, 64)

printing the one dimensional arrays

In [26]:
x[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

splitting the data

In [27]:
x_train = x[:1000]
y_train = y[:1000]


In [28]:
x_test = x[1000:]
y_test = y[1000:]

multi layer perception classifier